DROP TABLE MEMBER;
DROP SEQUENCE MEMBERSEQ;

CREATE SEQUENCE MEMBERSEQ;

CREATE TABLE MEMBER(
	MEMBER_ID NUMBER NOT NULL,
	MEMBER_NAME VARCHAR2(20) NOT NULL,
	MEMBER_EMAIL VARCHAR2(40) NOT NULL,
	MEMBER_PW VARCHAR2(30) NOT NULL,
	MEMBER_ROLE VARCHAR2(20) NOT NULL,
	CONSTRAINT MEMBER_PK_ID PRIMARY KEY(MEMBER_ID),
	CONSTRAINT MEMBER_UQ_EMAIL UNIQUE(MEMBER_EMAIL)
);

INSERT INTO MEMBER
VALUES(MEMBERSEQ.NEXTVAL,'관리자','A@A','123','ADMIN');

INSERT INTO MEMBER
VALUES(MEMBERSEQ.NEXTVAL,'홍길동','B@B','123','USER');

SELECT * FROM MEMBER ORDER BY MEMBER_ID DESC;






