
DROP TABLE COMMENT_TB;

DROP SEQUENCE COMMENT_ID;
DROP SEQUENCE GROUPNOSQ;

CREATE SEQUENCE COMMENT_ID;
CREATE SEQUENCE GROUPNOSQ;

CREATE TABLE COMMENT_TB(
	COMMENT_ID NUMBER NOT NULL, --댓글번호
	GROUPNO NUMBER NOT NULL, --그룹번호
	GROUPSQ NUMBER NOT NULL, --시퀀스그룹번호
	TITLETAB NUMBER NOT NULL, --답변
	MEMBER_ID NUMBER NOT NULL, -- 회원번호
	COMMENT_CONTENT VARCHAR2(2000) NOT NULL, --댓글내용
	REGDATE DATE NOT NULL, --댓글쓴날짜
	CONSTRAINT COMMENT_PK_ID PRIMARY KEY(COMMENT_ID),
	CONSTRAINT COMMENT_FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID)
);

SELECT * FROM COMMENT_TB;

INSERT INTO COMMENT_TB
VALUES(COMMENT_ID.NEXTVAL, GROUPNOSQ.NEXTVAL,1,0,1,'댓글',SYSDATE);