DROP TABLE MAKEBOARD;
DROP SEQUENCE MAKESEQ;

CREATE SEQUENCE MAKESEQ;
CREATE TABLE MAKEBOARD(
	MAKE_ID NUMBER PRIMARY KEY,
	MAKE_TITLE VARCHAR2(1000) NOT NULL,
	MAKE_CONTENT VARCHAR2(4000) NOT NULL,
	MAKE_REGDATE DATE NOT NULL,
	MEMBER_ID NUMBER CONSTRAINT MAKEBOARD_FK_MEMID REFERENCES MEMBER(MEMBER_ID)
);

INSERT INTO MAKEBOARD VALUES
(MAKESEQ.NEXTVAL,'첫번째 글','1번글입니다',SYSDATE,2);

INSERT INTO MAKEBOARD VALUES
(MAKESEQ.NEXTVAL,'첫번째 글','1번글입니다',SYSDATE,1);

COMMIT;