DROP TABLE RVCOMMENT;

DROP SEQUENCE RVMMENTSQ;
DROP SEQUENCE RVGROUPNOSQ;

CREATE SEQUENCE RVCOMMENTSQ;
CREATE SEQUENCE RVGROUPNOSQ;


CREATE TABLE RVCOMMENT(
	RVCOMMENT_ID NUMBER NOT NULL, --댓글번호
	RVGROUPNO NUMBER NOT NULL, --그룹번호
	RVGROUPSQ NUMBER NOT NULL, --시퀀스그룹번호
	RVTITLETAB NUMBER NOT NULL, --답변
	MEMBER_ID NUMBER NOT NULL, -- 회원번호
    MEMBER_NAME VARCHAR2(30) NOT NULL,
	RV_ID NUMBER NOT NULL, --QA번호
	RVCOMMENT_CONTENT VARCHAR2(2000) NOT NULL, --댓글내용
	RVREGDATE DATE NOT NULL, --댓글쓴날짜
	CONSTRAINT RVCOMMENT_PK_ID PRIMARY KEY(RVCOMMENT_ID),
	CONSTRAINT RVCOMMENT_FK_MEMBER_ID FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(MEMBER_ID),
	CONSTRAINT RVCOMMENT_FK_RV_ID FOREIGN KEY(RV_ID) REFERENCES RVDOCUMENT(RV_ID)
);